<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- accessories -->
  <link name="imu_link"></link>
  <joint name="imu_joint" type="fixed">
    <origin xyz="${0.025-chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    <parent link="chassis_link"/>
    <child link="imu_link"/>
  </joint>

  <link name="laser_link"></link>
  <joint name="laser_joint" type="fixed">
    <origin xyz="${0.045} 0 ${0.135}" rpy="0 0 0"/>
    <parent link="chassis_link"/>
    <child link="laser_link"/>
  </joint>
</robot>