<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- accessories -->
  <link name="imu_link">
    <visual>
      <geometry>
          <box size="0.036 0.039 0.005"/>
      </geometry>
      <material name="yellow"/>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="imu_link"/>
    <origin xyz="${0.025-chassis_length/2} 0 ${chassis_height/2 + 0.01}" rpy="0 0 0"/>
  </joint>


  <!-- depth camera -->
  <link name="camera_link">
      <visual>
          <geometry>
              <box size="0.02 0.095 0.02"/>
          </geometry>
          <material name="white"/>
      </visual>
  </link>
  <joint name="camera_joint" type="fixed">
      <parent link="chassis_link"/>
      <child link="camera_link"/>
      <origin xyz="0.07 0 0.065" rpy="0 0 0"/>
  </joint>



  <link name="camera_optical_link"></link>
  <joint name="camera_optical_joint" type="fixed">
      <parent link="camera_link"/>
      <child link="camera_optical_link"/>
      <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- realsense -->
  <!-- <link name="realsense_link">
    <visual name="realsense_link_visual">
        <pose>0 0 0 -1.57 0 -1.57</pose>
        <geometry>
          <mesh>
            <uri>model://zbot_stella_n2_description/models/realsense_camera/meshes/d435.dae</uri>
          </mesh>
        </geometry>
    </visual>
  </link> -->

  

  <!-- lidar -->
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
      <material name="red"/>
    </visual>
    <visual>
      <origin xyz="0 0 -0.05"/>
      <geometry>
          <cylinder radius="0.01" length="0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>
  
  <joint name="laser_joint" type="fixed">
    <origin xyz="${0.045} 0 ${0.135}" rpy="0 0 0"/>
    <parent link="chassis_link"/>
    <child link="laser_link"/>
  </joint>


</robot>